# -------------------------------------------------------------------------
# This is GFDL-specfic spack repository configuration. It includes the
# builtin spack package repository, custom spack repository, and modulefile
# template spack repository.
#
# Users can override these settings by editing the following files.
#
# Per-user settings (overrides default and site settings):
#   ~/.spack/repos.yaml
#package.py files used to be in var/spack/custom_repos/spack_repo/custom
#  cew:
#    git: https://github.com/cwhitlock-NOAA/custom_spack.git
#    branch: main
#    destination: $SPACK_ROOT/custom_repo
# -------------------------------------------------------------------------
repos:
  builtin:
    git: https://github.com/spack/spack-packages.git
    branch: releases/v2025.07
    destination: $SPACK_ROOT/package_repos
